#!/usr/bin/env python3

import sys
import argparse
import json
import subprocess

baseargs = [
    "rsync",
    "--hard-links",
    "--out-format", "%t %i %n%L", # like --itemize-changes, but with timestamp
    "--stats",
    "--recursive",
    "--update",
    "--delete",
    "--delete-after",
    "--delay-updates"
]

parser = argparse.ArgumentParser(add_help=False)
parser.add_argument('--config', dest='config', required=True)

args = parser.parse_args()
print(args.config)

with open(args.config) as config :
    data = json.load(config)

fail = False

for path, mirror in data["repos"].items():
    args = (baseargs +
        ["rsync://{mirror}/{path}/".format(mirror=mirror, path=path)] +
        ["{base}/{path}".format(base=data["base"], path=path)])
    print(" ".join(args))
    result = subprocess.call(args)
    if result != 0:
        fail = True

if fail:
    sys.exit(1)
